name: 'example'
description: 'Demonstrates how to use the sms_flutter plugin.'
publish_to: 'none'
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  sms_flutter:
    path: '../'
  cupertino_icons: '^1.0.2'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^4.0.0'
flutter:
  uses-material-design: true
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/general_framework'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
